# Generated by Django 4.1.6 on 2023-02-26 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contract_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=250)),
                ('sector', models.CharField(max_length=250)),
                ('project', models.CharField(max_length=250)),
                ('works_type', models.CharField(max_length=250)),
                ('contract_type', models.CharField(choices=[('توريد + تنفيذ', 'توريد + تنفيذ'), ('توريد', 'توريد'), ('تنفيذ', 'تنفيذ')], max_length=250)),
                ('contract_value', models.IntegerField()),
                ('contract_duration', models.IntegerField()),
                ('cost_istimation', models.CharField(choices=[('إنشاءات (أ)', 'إنشاءات (أ)'), ('بنية تحتية (ج)', 'بنية تحتية (ج)')], max_length=250)),
                ('name', models.CharField(max_length=250)),
                ('bank_account', models.IntegerField()),
                ('iban', models.IntegerField()),
                ('tax_number', models.IntegerField()),
                ('signature_authorization', models.FileField(blank=True, null=True, upload_to='')),
                ('delegated_nam', models.CharField(max_length=250)),
                ('delegated_title', models.CharField(max_length=250)),
                ('gov_id_no', models.CharField(max_length=250)),
                ('second_party_representative', models.CharField(max_length=250)),
                ('phone_no', models.IntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('postal_code', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=250)),
                ('commercial_register', models.FileField(upload_to='')),
                ('commercial_register_date', models.DateField()),
                ('manager_authorized_agent', models.CharField(max_length=250)),
                ('association_contract', models.FileField(upload_to='')),
                ('zakat_Income_certificate', models.FileField(upload_to='')),
                ('sub_contractor_profile', models.FileField(upload_to='')),
            ],
            options={
                'verbose_name': 'Contract_Detail',
                'ordering': ['id'],
            },
        ),
    ]
