# Generated by Django 4.1.6 on 2023-02-26 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_detail',
            name='payment_terms',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contract_detail',
            name='special_conditions',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
