# Generated by Django 4.1.6 on 2023-02-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0002_contract_detail_payment_terms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_detail',
            name='association_contract',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='commercial_register',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='signature_authorization',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sub_contractor_profile',
            field=models.FileField(upload_to='files'),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='zakat_Income_certificate',
            field=models.FileField(upload_to='files'),
        ),
    ]
