# Generated by Django 4.1.6 on 2023-02-26 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0004_alter_contract_detail_association_contract_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_detail',
            name='signature_authorization',
            field=models.FileField(null=True, upload_to='files'),
        ),
    ]
