# Generated by Django 4.1.6 on 2023-02-26 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0005_alter_contract_detail_signature_authorization'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contract_detail',
            name='creator',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='project',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='contract_detail',
            name='sector',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
