# Generated by Django 4.1.7 on 2023-03-20 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0042_remove_contract_detail_sgnlassign1_action_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_detail',
            name='extra_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
