# Generated by Django 4.1.7 on 2023-03-20 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0043_contract_detail_extra_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract_detail',
            name='extra_id',
        ),
    ]
