# Generated by Django 4.1.7 on 2023-03-21 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contract', '0044_remove_contract_detail_extra_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract_detail',
            name='extra_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
