# Generated by Django 4.1.6 on 2023-02-26 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tendering', '0029_alter_mngmnt_category_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='t_detail',
            name='photo_author',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
