# Generated by Django 4.1.6 on 2023-02-26 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_user_level_options_user_tenderpermission_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_profile',
            name='group1',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group10',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group11',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group12',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group2',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group3',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group4',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group5',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group6',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group7',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group8',
        ),
        migrations.RemoveField(
            model_name='user_profile',
            name='group9',
        ),
    ]
